name: Deploy-to-github

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: where am i
        uses: pwd
      - name: copy content of the main branch to the build folder
        run: cp * ./build -r
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
